name: test action
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: ./
       with:
         name: adamwizard.dll
         timestamp: 2728144711
         virtual_size: 937984
     - run: file adamwizard.dll